Addition: toy reservoir simulator
mralbu/awesome-reservoir-engineering pull request #2
Opened 2022-11-07 18:17 UTC by patnr

Project name:

Project website/repository:

License:

Checklist for new projects:

- [x] Project is [`certified awesome`](awesome.md)

- [x] The project is [open-source](https://opensource.org/licenses/alphabetical) and accessible.
- [x] Searched the existing entries to make sure this is not a duplicate.
- [x] Contains only a single addition (make separate PRs if adding more than one).
- [x] Added the link to the bottom of the relevant category.
- [ ] Created a new category only if necessary.

- [x] Link the repo rather than the website/documentation
- [x] Installation instructions present
- [x] Documentation looks great
- [x] Examples or Tutorials to follow
- [ ] Tests and Travis CI running

- [x] Add icon from the `media/icon/` folder if applicable (like `![Python](media/icon/python.png)` ).
- [x] Checked spelling and grammar.
- [x] Removed trailing whitespace and periods.
- [x] Confirm the dash – is not a minus -.
- [x] Used [title-casing](http://titlecapitalization.com) (AP style) for project name.

2022-12-09 21:16 UTC, mralbu requested changes
Hi @patnr, thanks for your contribution! Could you invert the order of the flags and the description, so as to maintain the same order as other entries? The order would be - []() ![](flags) description, like the example bellow
- [TPFA-ResSim](https://github.com/patnr/TPFA-ResSim)  - ![Python](media/icon/python.png) ![Matlab](media/icon/matlab.png) Toy petroleum reservoir simulator using TPFA

2022-12-16 12:01 UTC, patnr commented
Of course, my bad!

2022-12-17 02:59 UTC, mralbu approved these changes

2022-12-17 02:59 UTC, merged

2022-12-17 03:00 UTC, mralbu commented
Thank you!